version: '3.8'

services:
  gestion-produits-postgres:
    image: postgres:latest
    container_name: compose-postgres
    networks:
      - pont
    environment:
      POSTGRES_DB: gestion_produits
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"

  gestion-produits-php:
    build:
      context: .
      dockerfile: DockerfilePHP
    container_name: compose-php
    image: gestion-produits-php
    networks:
      - pont
    ports:
      - "8080:80"
    depends_on:
      - gestion-produits-postgres

networks:
  pont:
    driver: bridge
