version: '3.8'

services:
  gestion-produits-mysql:  
    build:
      context: .
      dockerfile: DockerfileSql
    container_name: compose-mysql8.3
    image: gestion-mysql8
    networks:
      - pont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
    ports:
      - "3306:3306"  

  gestion-produits-php:  
    build:
      context: .
      dockerfile: DockerfilePHP
    container_name: compose-php8.3
    image: gestion-php8
    networks:
      - pont
    ports:
      - "8080:80"  
    depends_on:
      - gestion-produits-mysql  

networks:
  pont:  
    driver: bridge
